METODO GROUPBY

In [4]:
import pandas as pd

from datetime import datetime

facturas = pd.DataFrame({'folio':(15234,

           15235,

           15236,

           15237,

           15238,

           15239,

           15240,

           15241,

           15242),

      'sucursal':('CDMX01',

            'MTY01',

            'CDMX02',

            'CDMX02',

            'MTY01',

            'GDL01',

            'CDMX02',

            'MTY01',

            'GDL01'),

      'monto':(1420.00,

          1532.00,

          890.00,

          1300.00,

          3121.47,

          1100.5,

          12230,

          230.85,

          1569),

      'fecha':(datetime(2019,3,11,17,24),

          datetime(2019,3,24,14,46),

          datetime(2019,3,25,17,58),

          datetime(2019,3,27,13,11),

          datetime(2019,3,31,10,25),

          datetime(2019,4,1,18,32),

          datetime(2019,4,3,11,43),

          datetime(2019,4,4,16,55),

          datetime(2019,4,5,12,59)),

     'cliente':(19234,

           19232,

           19235,

           19233,

           19236,

           19237,

           19232,

           19233,

           19232)

})

In [6]:
gastosporcliente= facturas.filter(items=["monto","cliente"])
print(gastosporcliente)

      monto  cliente
0   1420.00    19234
1   1532.00    19232
2    890.00    19235
3   1300.00    19233
4   3121.47    19236
5   1100.50    19237
6  12230.00    19232
7    230.85    19233
8   1569.00    19232

In [16]:
clientes = gastosporcliente.groupby("cliente")
print(clientes.groups)

{19232: [1, 6, 8], 19233: [3, 7], 19234: [0], 19235: [2], 19236: [4], 19237: [5]}

In [ ]:
for nombre_cliente , grupo in clientes:
  print(f"Grupo para cliente: (nombre_clientes)")

In [17]:
clientes.max()

            monto
cliente
19232    12230.00
19233     1300.00
19234     1420.00
19235      890.00
19236     3121.47
19237     1100.50

In [19]:
clientes.min()

           monto
cliente
19232    1532.00
19233     230.85
19234    1420.00
19235     890.00
19236    3121.47
19237    1100.50

In [20]:
clientes.size()

cliente
19232    3
19233    2
19234    1
19235    1
19236    1
19237    1
dtype: int64

Limpieza de datos faltantes

In [23]:
import pandas as pd
import numpy as np

In [24]:
poblacion=pd.DataFrame({'Animal':('lobo','coyote','jaguar','cerdosalvaje',
'tapir','venado','ocelote','puma'),
'Norte_I':(12,np.nan,None,2,4,2,14,5),
'Norte_II':(23,4,25,21,9,121,1,2),
'Centro_I':(15,23,2,120,40,121,0,5),
'Sur_I':(28,46,14,156,79,12,2,np.nan)}).set_index('Animal')

In [25]:
poblacion

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
coyote            NaN         4        23   46.0
jaguar            NaN        25         2   14.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0
puma              5.0         2         5    NaN

In [26]:
poblacion.isna()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo            False     False     False  False
coyote           True     False     False  False
jaguar           True     False     False  False
cerdosalvaje    False     False     False  False
tapir           False     False     False  False
venado          False     False     False  False
ocelote         False     False     False  False
puma            False     False     False   True

In [28]:
poblacion.isna().sum()

Norte_I     2
Norte_II    0
Centro_I    0
Sur_I       1
dtype: int64

In [29]:
poblacion.isnull().sum()

Norte_I     2
Norte_II    0
Centro_I    0
Sur_I       1
dtype: int64

In [31]:
poblacion.notna()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             True      True      True   True
coyote          False      True      True   True
jaguar          False      True      True   True
cerdosalvaje     True      True      True   True
tapir            True      True      True   True
venado           True      True      True   True
ocelote          True      True      True   True
puma             True      True      True  False

In [32]:
poblacion.notna().sum()

Norte_I     6
Norte_II    8
Centro_I    8
Sur_I       7
dtype: int64

In [33]:
poblacion.shape

(8, 4)

In [34]:
poblacion.fillna(0)

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
coyote            0.0         4        23   46.0
jaguar            0.0        25         2   14.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0
puma              5.0         2         5    0.0

In [36]:
poblacion.fillna("Invalido")

               Norte_I  Norte_II  Centro_I     Sur_I
Animal
lobo              12.0        23        15      28.0
coyote        Invalido         4        23      46.0
jaguar        Invalido        25         2      14.0
cerdosalvaje       2.0        21       120     156.0
tapir              4.0         9        40      79.0
venado             2.0       121       121      12.0
ocelote           14.0         1         0       2.0
puma               5.0         2         5  Invalido

In [37]:
poblacion.dropna()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0

In [43]:
poblacion1= poblacion.dropna()
print(poblacion1)

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0

In [52]:
promedio= int(sum(poblacion1["Norte_I"])/len(poblacion1["Norte_I"]))
poblacion ["Norte_I"].fillna(promedio)

Animal
lobo            12.0
coyote           6.0
jaguar           6.0
cerdosalvaje     2.0
tapir            4.0
venado           2.0
ocelote         14.0
puma             5.0
Name: Norte_I, dtype: float64

In [51]:
poblacion.round()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
coyote            NaN         4        23   46.0
jaguar            NaN        25         2   14.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0
puma              5.0         2         5    NaN

In [56]:
poblacion.duplicated()

Animal
lobo            False
coyote          False
jaguar          False
cerdosalvaje    False
tapir           False
venado          False
ocelote         False
puma            False
dtype: bool

Otra base de datos:

In [62]:
otra_poblacion=pd.DataFrame({'Animal':('lobo','coyote','jaguar','cerdosalvaje',
'tapir','venado','ocelote','puma'),
'Norte_I':(12,4,None,2,4,2,14,4),
'Norte_II':(23,4,25,21,9,121,1,4),
'Centro_I':(15,4,2,120,40,121,0,4),
'Sur_I':(28,4,14,156,79,12,2,4)}).set_index('Animal')
print(otra_poblacion)

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15     28
coyote            4.0         4         4      4
jaguar            NaN        25         2     14
cerdosalvaje      2.0        21       120    156
tapir             4.0         9        40     79
venado            2.0       121       121     12
ocelote          14.0         1         0      2
puma              4.0         4         4      4

In [60]:
otra_poblacion.duplicated()

Animal
lobo            False
coyote          False
jaguar          False
cerdosalvaje    False
tapir           False
venado          False
ocelote         False
puma             True
dtype: bool

In [63]:
otra_poblacion.drop_duplicates()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15     28
coyote            4.0         4         4      4
jaguar            NaN        25         2     14
cerdosalvaje      2.0        21       120    156
tapir             4.0         9        40     79
venado            2.0       121       121     12
ocelote          14.0         1         0      2

LECTURA CON **PANDAS**

In [65]:
otra_poblacion.head()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15     28
coyote            4.0         4         4      4
jaguar            NaN        25         2     14
cerdosalvaje      2.0        21       120    156
tapir             4.0         9        40     79

In [66]:
otra_poblacion.tail()

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
cerdosalvaje      2.0        21       120    156
tapir             4.0         9        40     79
venado            2.0       121       121     12
ocelote          14.0         1         0      2
puma              4.0         4         4      4

In [67]:
otra_poblacion.tail(3)

         Norte_I  Norte_II  Centro_I  Sur_I
Animal
venado       2.0       121       121     12
ocelote     14.0         1         0      2
puma         4.0         4         4      4

In [68]:
otra_poblacion.isin((20,31))

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo            False     False     False  False
coyote          False     False     False  False
jaguar          False     False     False  False
cerdosalvaje    False     False     False  False
tapir           False     False     False  False
venado          False     False     False  False
ocelote         False     False     False  False
puma            False     False     False  False

In [72]:
otra_poblacion.isin((28,31)).sum()

Norte_I     0
Norte_II    0
Centro_I    0
Sur_I       1
dtype: int64

In [75]:
poblacion.dropna(inplace=True)
poblacion

              Norte_I  Norte_II  Centro_I  Sur_I
Animal
lobo             12.0        23        15   28.0
cerdosalvaje      2.0        21       120  156.0
tapir             4.0         9        40   79.0
venado            2.0       121       121   12.0
ocelote          14.0         1         0    2.0

In [4]:
poblacion.drop(["Centro_I"], axis=1, inplace = True)
poblacion

NameError: name 'poblacion' is not defined